# Input topics handled/muxed.
# TODO: Remove /demo/cmd_vel once the demo node is
# merged into the executive.

topics:
-
  name    : navigation
  topic   : /navigation/cmd_vel
  timeout : 0.5
  priority: 100
-
  name    : teleop
  topic   : /teleop/cmd_vel
  timeout : 0.5
  priority: 150
-
  name    : demo
  topic   : /demo/cmd_vel
  timeout : 0.5
  priority: 50
